name: numix-icon-theme
title: Numix Icons
version: '25.01.31'
summary: Numix is the official icon theme from the Numix Project.
description: |
  A Snap for the Numix icon theme.

build-base: core20
base: bare
grade: stable
confinement: strict
license: GPL-3.0
icon: snap/local/numix.png

architectures:
  - build-on: amd64
    run-on: all

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Numix
        - $SNAP/share/icons/Numix-Light

parts:
  icons:
    after:
      - utils
    plugin: dump
    source: "https://github.com/numixproject/numix-icon-theme/archive/refs/tags/$SNAPCRAFT_PROJECT_VERSION.tar.gz"
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
        mv $SNAPCRAFT_PART_INSTALL/Numix* $SNAPCRAFT_PART_INSTALL/share/icons/
        $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/Numix*
        
  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
